name: Run Tests
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          pwd
          mkdir build
          (cd build && pwd && ls)
          (cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=install ..)
          (cd build && make)

      - name: Run tests
        run: make test
