name: Run Tests
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          mkdir build
          (cd build && cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=install ..)
          (cd build && make)

      - name: Run tests
        run: |
          (cd build && make check)
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: |
          apt install sox
          python -m pip install --upgrade pip
          pip install -r requirements.dev.txt
          pip install .
      - name: Run tests
        run: pytest
